### PR TITLE
Fix crash on recursive interrupt ID

### LINKED ISSUE #473: Luacontroller recursive table interrupt iid crash
Server crash POC:
```lua
hax = {}
hax.a = hax
interrupt(1, hax)
```
After browsing the source I've found that the iid is passed to add_action without serialization ([init.lua](https://github.com/minetest-mods/mesecons/blob/master/mesecons_luacontroller/init.lua#L298))
```lua
local msg_ser = minetest.serialize(iid)
if #msg_ser <= mesecon.setting("luacontroller_interruptid_maxlen", 256) then
	mesecon.queue:add_action(pos, "lc_interrupt", {luac_id, iid}, time, iid, 1)
else
```

### PR DESCRIPTION
**Pull request by numberZero**
Fix #473.
This ensures the interrupt ID, if it is a table, is a proper tree. A DAG wouldn’t crash the server either but checking for that is tricky.
This also deprecates non-string IIDs to allow future simplifications. Interrupt ID isn’t a place to store tables.

### CODE REVIEW

File: mesecons_luacontroller/init.lua [hunk 1]
```diff
@@ -266,6 +266,46 @@ local function remove_functions(x)
...
+		if #iid <= limit then return true end -- string is OK unless too long
+		return false, "An interrupt ID was too large!"
+	end
+	if type(iid) == "number" or type(iid) == "boolean" then return true, "Non-string interrupt IDs are deprecated" end
+
+	local warn
+	local seen = {}
+	local function check(t)
+		if type(t) == "function" then
+			warn = "Functions can't be used in interrupt IDs"
```
Comment (sfan5) [inline mesecons_luacontroller/init.lua:283]:
```suggestion
			warn = "Functions cannot be used in interrupt IDs"
```

**Review by sfan5 — APPROVED** [review]
Looks good otherwise
