### PR TITLE
fix unloaded active button staying on for ever

### LINKED ISSUE #325: button stays on if unloaded while active
If a button was unloaded while it was activated, it doesn't get deactivated again and stays activated.
To test this you can press a button and press escape (in singleplayer) and leave and then join again.

### PR DESCRIPTION
**Pull request by DS-Minetest**
Fixes #325.

### CODE REVIEW

File: mesecons_button/init.lua [hunk 1]
```diff
@@ -45,7 +46,7 @@ minetest.register_node("mesecons_button:button_off", {
 		minetest.swap_node(pos, {name = "mesecons_button:button_on", param2=node.param2})
 		mesecon.receptor_on(pos, mesecon.rules.buttonlike_get(node))
 		minetest.sound_play("mesecons_button_push", {pos=pos})
-		minetest.after(1, mesecon.button_turnoff, pos)
+		minetest.get_node_timer(pos):start(1)
```
Comment (numberZero) [inline mesecons_button/init.lua]: hard-coded value

Comment (DS-Minetest) [inline mesecons_button/init.lua]: Is there any reason to make it configurable?

Comment (numberZero) [inline mesecons_button/init.lua]: Don’t think so, just don’t like magic numbers. But that’s not really a problem, at least as long as such number is used in one place only ;)
