### PR TITLE
Make some fixes to movement and rotation

### LINKED ISSUE #517: Gates do not update when rotated
If you rotate a gate with mtg's screwdriver, the connected wires do not update correctly.

Example:
screenshot_20200628_141721

### PR DESCRIPTION
**Pull request by TurkeyMcMac**
Fixes:
- Gates, conductors, and buttonlike components (e.g. buttons) now update things correctly when rotating (fixes #517.)
- Conductors that are turned on do not become stuck in this state when pushed by pistons (they update correctly.)

I did various tests, which you can download as WorldEdit schematics:
- [ex-recv-horiz.we.gz](https://github.com/minetest-mods/mesecons/files/7954363/ex-recv-horiz.we.gz): The wires should not get into the wrong state as you rotate the lever node around its axis.
- [ex-recv-vert.we.gz](https://github.com/minetest-mods/mesecons/files/7954364/ex-recv-vert.we.gz): The wires should not get into the wrong state as you rotate the button node around its axis.
- [ex-rot-and.we.gz](https://github.com/minetest-mods/mesecons/files/7954365/ex-rot-and.we.gz): The wires and the AND gate should not get into the wrong state as you rotate the AND gate node around its axis.
- [ex-rot-tee.we.gz](https://github.com/minetest-mods/mesecons/files/7954366/ex-rot-tee.we.gz): The wires and the piston should not get into the wrong state as you rotate the T-junction wire node around its axis.
- [ex-piston-strobe.we.gz](https://github.com/minetest-mods/mesecons/files/7954358/ex-piston-strobe.we.gz): When you place a wire in front of the piston, it should start going on and off really fast. It might not be in the right state when you break the wire, but that's a separate issue.
- [ex-push-and.we.gz](https://github.com/minetest-mods/mesecons/files/7954359/ex-push-and.we.gz): When you activate the piston, the AND gate should start flashing on and off then overheat.
- [ex-push-cond-dc.we.gz](https://github.com/minetest-mods/mesecons/files/7954360/ex-push-cond-dc.we.gz): After you activate the piston, the wires should be in the correct state.
- [ex-push-cond-loop.we.gz](https://github.com/minetest-mods/mesecons/files/7954361/ex-push-cond-loop.we.gz): After you activate the piston, the wires should be in the correct state.
- [ex-push-nor.we.gz](https://github.com/minetest-mods/mesecons/files/7954362/ex-push-nor.we.gz): When you activate the first piston, the second piston should activate then deactivate really fast.

### CODE REVIEW

File: mesecons/services.lua [hunk 1]
```diff
@@ -11,18 +12,20 @@ mesecon.on_placenode = function(pos, node)
 	-- Conductors: Send turnon signal when powered or replace by respective offstate conductor
 	-- if placed conductor is an onstate one
 	if mesecon.is_conductor(node.name) then
+		local conductor = mesecon.get_conductor(node.name)
+		if conductor.state ~= mesecon.state.off then
+			-- Turn the conductor off.
+			node.name = conductor.offstate or conductor.states[1]
```
Comment (sfan5) [inline mesecons/services.lua:18]: Why not `node.name = mesecon.get_conductor_off(node)`?

File: mesecons/services.lua [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 mesecon.on_placenode = function(pos, node)
 	mesecon.execute_autoconnect_hooks_now(pos, node)
+	node = minetest.get_node(pos)
```
Comment (sfan5) [inline mesecons/services.lua:5]: I assume `execute_autoconnect_hooks_now` may change the node, a comment should point out why the get_node here is needed

File: mesecons/services.lua (hunk 1 above)
Comment (TurkeyMcMac) [reply mesecons/services.lua:18]: `mesecon.get_conductor_off` seems to work differently for conductors with more than two states. I think it only sets one of the state bits to zero.

**Review by sfan5 — APPROVED** [review]
LGTM

**Comment by sfan5** [comment]
Was that a rebase or any changes?

**Comment by TurkeyMcMac** [comment]
Just a rebase.
